### PR TITLE
Correct ambiguous text in README

### PR DESCRIPTION
**Pull request by Sohex**
This closes https://github.com/google/highway/issues/2065

### CODE REVIEW

**Comment by jan-wassenberg** [comment]
Thank you for pointing this out and fixing it :) Are you able to sign the CLA?

**Comment by Sohex** [comment]
Yep, I did!

**Comment by jan-wassenberg** [comment]
:) Looks like the bot has not yet picked it up. Is it signed with the same email address that made the git commit?

**Comment by Sohex** [comment]
It is, I just triggered a rescan and it looks like it's good now.

**Review by jan-wassenberg — APPROVED** [review]
Thanks :)

**Pull request merged**
