### PR TITLE
use O(N) build-heap in vqsort

### PR DESCRIPTION
**Pull request by QuarticCat**
The previous build-heap algorithm is O(N*logN).

Reference: *Introduction to Algorithms*, third edition, chap 6.3

### CODE REVIEW

**Comment by QuarticCat** [comment]
My CPU is Ryzen 3700X.

Before this commit:

```text
[ RUN      ] BenchSortGroup/BenchSort.BenchAllSort/AVX2
      AVX2:          std:     f32: uniform32: 1.00E+06   59 MB/s ( 1 threads)
      AVX2:         heap:     f32: uniform32: 1.00E+06   25 MB/s ( 1 threads)
      AVX2:           vq:     f32: uniform32: 1.00E+06  791 MB/s ( 1 threads)
      AVX2:          std:     i32: uniform32: 1.00E+06   71 MB/s ( 1 threads)
      AVX2:         heap:     i32: uniform32: 1.00E+06   30 MB/s ( 1 threads)
      AVX2:           vq:     i32: uniform32: 1.00E+06  753 MB/s ( 1 threads)
      AVX2:          std:     i64: uniform32: 1.00E+06  142 MB/s ( 1 threads)
      AVX2:         heap:     i64: uniform32: 1.00E+06   60 MB/s ( 1 threads)
      AVX2:           vq:     i64: uniform32: 1.00E+06  757 MB/s ( 1 threads)
      AVX2:          std:    u128: uniform32: 1.00E+06  147 MB/s ( 1 threads)
      AVX2:         heap:    u128: uniform32: 1.00E+06   60 MB/s ( 1 threads)
      AVX2:           vq:    u128: uniform32: 1.00E+06  708 MB/s ( 1 threads)
[       OK ] BenchSortGroup/BenchSort.BenchAllSort/AVX2 (25606 ms)
```

After this commit:

```text
[ RUN      ] BenchSortGroup/BenchSort.BenchAllSort/AVX2
      AVX2:          std:     f32: uniform32: 1.00E+06   61 MB/s ( 1 threads)
      AVX2:         heap:     f32: uniform32: 1.00E+06   26 MB/s ( 1 threads)
      AVX2:           vq:     f32: uniform32: 1.00E+06  830 MB/s ( 1 threads)
      AVX2:          std:     i32: uniform32: 1.00E+06   72 MB/s ( 1 threads)
      AVX2:         heap:     i32: uniform32: 1.00E+06   32 MB/s ( 1 threads)
      AVX2:           vq:     i32: uniform32: 1.00E+06  836 MB/s ( 1 threads)
      AVX2:          std:     i64: uniform32: 1.00E+06  148 MB/s ( 1 threads)
      AVX2:         heap:     i64: uniform32: 1.00E+06   62 MB/s ( 1 threads)
      AVX2:           vq:     i64: uniform32: 1.00E+06  759 MB/s ( 1 threads)
      AVX2:          std:    u128: uniform32: 1.00E+06  149 MB/s ( 1 threads)
      AVX2:         heap:    u128: uniform32: 1.00E+06   62 MB/s ( 1 threads)
      AVX2:           vq:    u128: uniform32: 1.00E+06  713 MB/s ( 1 threads)
[       OK ] BenchSortGroup/BenchSort.BenchAllSort/AVX2 (24349 ms)
```

Improvement is not quite significant and varies on my machine. But generally the O(N) build-heap version is slightly faster.

**Comment by jan-wassenberg** [comment]
Thanks @QuarticCat for the patch! Would you mind adding some comments to the SiftDown function?

I notice that the second run seems to be faster across the board. Let's check whether there may be some throttling going on. If CPU temp hits 90, I believe AMD will throttle. We can verify that with `perf stat -e cycles,ref-cycles bench_sort`.

Do we know the CPU temps? Lower = less leakage power, which may indirectly allow higher frequencies (by enabling higher voltage without reaching the power cap).

**Comment by QuarticCat** [comment]
The `SiftDown` function is basically copied from the original `HeapSort`'s sift-down part. I just modified some variable names.

**Comment by QuarticCat** [comment]
It seems that `ref-cycles` is not supported on my machine.

From `sensors`, my CPU temp is floating between 76°C and 79°C during the benchmark.

**Comment by QuarticCat** [comment]
To make the result more accurate, I tried the following steps:

1. Fix CPU frequency

```console
$ sudo cpupower frequency-set -u 3G -d 3G
```

From `watch -n 0 rg \"cpu MHz\" /proc/cpuinfo` I can observe that the CPU frequencies are fixed to `3600 MHz` (not 3G, I don't know why).

However, I can still see some cores are boosted to 4.2 GHz during the benchmark.

2. Disable boost

```console
$ sudo sh -c 'echo 0 > /sys/devices/system/cpu/cpufreq/boost'
```

Now the boost disappears. But the benchmark results are still floating.

3. Warm up and run multiple times

First I disabled most benches. Below is what it looks like now.

```text
> bazel-bin/hwy/contrib/sort/bench_sort
Running main() from gmock_main.cc
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from BenchSortGroup/BenchSort
[ RUN      ] BenchSortGroup/BenchSort.BenchAllSort/AVX2
      AVX2:         heap:     i32: uniform32: 1.00E+06   27 MB/s ( 1 threads)
      AVX2:         heap:     i64: uniform32: 1.00E+06   52 MB/s ( 1 threads)
[       OK ] BenchSortGroup/BenchSort.BenchAllSort/AVX2 (9227 ms)
[ RUN      ] BenchSortGroup/BenchSort.BenchAllSort/SSE4
[       OK ] BenchSortGroup/BenchSort.BenchAllSort/SSE4 (0 ms)
[ RUN      ] BenchSortGroup/BenchSort.BenchAllSort/SSSE3
[       OK ] BenchSortGroup/BenchSort.BenchAllSort/SSSE3 (0 ms)
[ RUN      ] BenchSortGroup/BenchSort.BenchAllSort/Emu128
[       OK ] BenchSortGroup/BenchSort.BenchAllSort/Emu128 (0 ms)
[----------] 4 tests from BenchSortGroup/BenchSort (9227 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test suite ran. (9227 ms total)
[  PASSED  ] 4 tests.
```

Then I use hyperfine to run this benchmark multiple times.

```console
$ hyperfine --warmup=2 --runs=10 'bazel-bin/hwy/contrib/sort/bench_sort'
```

Here are the final results.

Before this commit:

```text
Benchmark 1: bazel-bin/hwy/contrib/sort/bench_sort
  Time (mean ± σ):      9.502 s ±  0.020 s    [User: 9.491 s, System: 0.002 s]
  Range (min … max):    9.477 s …  9.545 s    10 runs
```

After this commit:

```text
Benchmark 1: bazel-bin/hwy/contrib/sort/bench_sort
  Time (mean ± σ):      9.267 s ±  0.018 s    [User: 9.256 s, System: 0.003 s]
  Range (min … max):    9.240 s …  9.308 s    10 runs
```

I am completely a beginner at benchmarking. You can pull this PR and bench it by yourself.

If you accept this PR, I will solve conflicts a few hours later. Now I need to sleep for a while.

**Comment by QuarticCat** [comment]
Any updates?

**Comment by jan-wassenberg** [comment]
@QuarticCat nice, looks like you have done more extensive benchmarking than is often the case, and it looks like a solid win :) We're happy to accept this PR after you sync it to HEAD.

**Comment by QuarticCat** [comment]
Updated. @jan-wassenberg

**Pull request merged**
