### PR TITLE
Cast __ppc_get_timebase_freq to double

### LINKED ISSUE #343: PPC64le + GCC 11.2.1: error: conversion from 'uint64_t' {aka 'long unsigned int'} to 'double' may change value
Some casting issue maybe?

```
[  8%] Building CXX object CMakeFiles/hwy.dir/hwy/nanobenchmark.cc.o
/usr/bin/g++  -I/builddir/build/BUILD/highway-0.14.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mcpu=power8 -mtune=power8 -fasynchronous-unwind-tables -fstack-clash-protection -O2 -g -DNDEBUG -fPIC -Wno-builtin-macro-redefined -D__DATE__=\"redacted\" -D__TIMESTAMP__=\"redacted\" -D__TIME__=\"redacted\" -fmerge-all-constants -Werror -Wall -Wextra -Wconversion -Wsign-conversion -Wvla -Wnon-virtual-dtor -fmath-errno -fno-exceptions -std=c++11 -MD -MT CMakeFiles/hwy.dir/hwy/nanobenchmark.cc.o -MF CMakeFiles/hwy.dir/hwy/nanobenchmark.cc.o.d -o CMakeFiles/hwy.dir/hwy/nanobenchmark.cc.o -c /builddir/build/BUILD/highway-0.14.1/hwy/nanobenchmark.cc
/builddir/build/BUILD/highway-0.14.1/hwy/nanobenchmark.cc: In function 'double hwy::platform::InvariantTicksPerSecond()':
/builddir/build/BUILD/highway-0.14.1/hwy/nanobenchmark.cc:403:33: error: conversion from 'uint64_t' {aka 'long unsigned int'} to 'double' may change value [-Werror=conversion]
  403 |   return __ppc_get_timebase_freq();
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~
```

Full log at https://koji.fedoraproject.org/koji/taskinfo?taskID=74091486

### PR DESCRIPTION
**Pull request by eclipseo**
Fix #343

### CODE REVIEW

**Review by jan-wassenberg — APPROVED** [review]

**Comment by jan-wassenberg** [comment]
Thanks for fixing this :) FYI we enabled some additional warnings (which I was surprised to see are not included in -Wall -Wextra) and added -Werror to prevent regressions, but have not compiled the PPC codepaths since then.

**Comment by jan-wassenberg** [comment]
@eclipseo would another 0.14.x release soon be helpful? Otherwise, the next one in a few weeks would include this.

**Comment by eclipseo** [comment]
> @eclipseo would another 0.14.x release soon be helpful? Otherwise, the next one in a few weeks would include this.

Not necessary for me as I added the change as a patch to my build. I don't know if any other distribution encountered the issue though. It might appear when building JPEG XL with submodules too. PPC is probably not very used with it.

**Comment by jan-wassenberg** [comment]
@eclipseo got it, thanks. IIRC Firefox does build for ppc. We'll do a release ~next week.

**Pull request merged**
