### PR TITLE
Add Get/Set for vectors and use them to implement Concat* operators for RVV

### PR DESCRIPTION
**Pull request by lsrcz**
This pull request

1. implements the `Get` and `Set` operators for RVV, which correspond to the `__riscv_vget*` and `__riscv_vset*` intrinsics, respectively.
2. optimizes the `Concat*` operators with `Get` and `Set`.

There are new type categories introduced (`_GET_SET`, `_GET_SET_VIRT`, `_GET_SET_SMALLEST`). The reason why new categories are introduces is:

1. RVV only provide `vget` and `vset` intrinsics for non-fractional vector types as the whole register movement instructions are only available for LMUL >= 1. This corresponds to the `_GET_SET` category. We cannot simply reuse the `_TRUNC` category as it contains fractional vector types.
2. The `_GET_SET_VIRT` category simulates the intrinsics using instructions other than whole register movement. The result is a register with half in LMUL.
3. Similar to `LowerHalf`, it is useful to have `Get` and `Set` also for the smallest LMUL for each SEW. This is the `_GET_SET_SMALLEST` category, and the result would be the same as the original register type for this category.

For the `Get` operator for fractional vector types, we use `Trunc`, which is effectively a no-op, to extract the lower part, and we use `SlideDown` for the upper parts.

For the `Set` operator for fractional vector types, we use `vmv` with the tail undisturbed configuration to set the lower part. We use `SlideUp` for the upper parts.

The `Concat` operator can then be optimized with `Get` and `Set`. For operators other than `ConcatLowerUpper`, we need a `Get` and a `Set`, and the program should be optimal for all SEW/LMUL combinations. For the `ConcatLowerUpper` operator, we will need two `Get`s and two `Set`s. This would be optimal only when the `Get` operation is always a no-op, meaning that the LMUL for the extracted part must be greater or equal to zero.

### CODE REVIEW

**Comment by johnplatts** [comment]
@lsrcz Could you please go ahead and merge the changes that I made in the lsrcz_hwy_concat_fixes_120224 branch of the https://github.com/johnplatts/jep_google_highway repository (which can be found at https://github.com/johnplatts/jep_google_highway/commit/914cb69c58c814e70d757ddc4d158e7c27ee43e8) into this pull request?

Here are the git commands for merging the changes in commit https://github.com/johnplatts/jep_google_highway/commit/914cb69c58c814e70d757ddc4d158e7c27ee43e8:
```
git remote add jep_hwy https://github.com/johnplatts/jep_google_highway.git
git fetch jep_hwy lsrcz_hwy_concat_fixes_120224
git merge jep_hwy/lsrcz_hwy_concat_fixes_120224
```

**Comment by lsrcz** [comment]
Hi @johnplatts, thanks for the changes! I am super busy at this time, but I will try to have a look at it as soon as possible.

**Comment by lsrcz** [comment]
Hi @johnplatts,

I finally got time to look at it -- thank you for your excellent work!

I think your solution addresses the issue in the original code where partial vectors weren't handled correctly (related to #2345), which I hadn't had time to resolve. It's an elegant approach, and I'll submit the code for review.

**Review by jan-wassenberg — APPROVED** [review]
Very nice, thank you @johnplatts and @lsrcz :)

**Comment by johnplatts** [comment]
@jan-wassenberg What was causing the feedback/copybara check from failing? Are there any additional changes that still need to be made to hwy/ops/rvv-inl.h, or does CI need to be re-run?

**Comment by jan-wassenberg** [comment]
We had an unrelated internal failure, sorry about that. Re-running now.

**Pull request merged**
