### PR TITLE
Added algo inl files to HWY_CONTRIB_SOURCES

### PR DESCRIPTION
**Pull request by nielskm**
The copy-inl.h, find-inl.h, and transform-inl.h headers are not installed when building highway with cmake.

### CODE REVIEW

**Comment by jan-wassenberg** [comment]
@nielskm thank you! Would you mind signing the CLA for this email address?

**Comment by nielskm** [comment]
> @nielskm thank you! Would you mind signing the CLA for this email address?

I believe I already did? At least I signed one for my gmail and then I updated the email address with git and pushed a new commit. But you're right - it doesn't seem to work...

**Comment by jan-wassenberg** [comment]
:) Yes, the bot is aware of the previous commit (https://github.com/google/highway/commit/27344c8d01e8130818a31be5982b072e237768e1 Author: <n**​@kvantify.dk>) and thinks it is part of this PR, even though it has been overwritten by the next.

You might try squashing all commits via git rebase -i?

**Comment by jan-wassenberg** [comment]
In https://github.com/google/highway/pull/905/commits we can see the commits. After rebase -i (using s for all commits except the main one, to "squash"), we hopefully will see only one commit in the list.

**Comment by nielskm** [comment]
Okay, I believe it works now.

**Comment by jan-wassenberg** [comment]
:) @nielskm looks good now, thanks, beginning the import process now..

**Pull request merged**
