### PR TITLE
Added Hypot op

### PR DESCRIPTION
**Pull request by johnplatts**
Added Hypot op to math-inl.h.

`Hypot(d, a, b)` returns the same result as `std::hypot(a[i], b[i])` if `a[i]` and `b[i]` are both non-NaN values, and `Hypot(d, a, b)` returns NaN if either `a[i]` or `b[i]` is NaN.

`Hypot(d, a, b)` is equivalent to `Sqrt(MulAdd(a, a, Mul(b, b)))`, but `Hypot(d, a, b)` will scale both `a[i]` and `b[i]` down prior to the multiplications if necessary to ensure that the multiplication ops result in finite values if `a[i]` and `b[i]` are both finite values.

### CODE REVIEW

**Review by jan-wassenberg — APPROVED** [review]
Very nice, thanks for adding :) I'll remove hypot from op_wishlist.md.

**Comment by jan-wassenberg** [comment]
We have some issues on Arm7, which does not properly support Inf/NaN:
```
[ RUN      ] HwyMathTestGroup/HwyMathTest.TestAllHypot/NEON_WITHOUT_AES
f32x4: Hypot(0.000000, inf) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(inf, 0.000000) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(-0.000000, inf) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(inf, -0.000000) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(1.000000, inf) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(inf, 1.000000) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(-1.000000, inf) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(inf, -1.000000) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(2.000000, inf) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(inf, 2.000000) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(-2.000000, inf) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(inf, -2.000000) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(0.000000, -inf) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(-inf, 0.000000) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(-0.000000, -inf) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(-inf, -0.000000) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(1.000000, -inf) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(-inf, 1.000000) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(-1.000000, -inf) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(-inf, -1.000000) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(2.000000, -inf) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(-inf, 2.000000) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(-2.000000, -inf) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(-inf, -2.000000) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(85070586659632214952926045871129231360.000000, inf) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot(inf, 85070586659632214952926045871129231360.000000) expected INF actual NAN ulp 4.1943e+06 max ulp 4
f32x4: Hypot max_ulp 4.1943e+06
Abort at math_test.cc:586: Assert max_ulp <= kMaxErrorUlp
```
Given the HW is not standards-compliant (in its defence, IEEE-754 changed between 2008 and 2019), I'd be fine to skip such tests for Armv7. highway_test also contains logic like `HWY_TARGET <= HWY_NEON_WITHOUT_AES && HWY_ARCH_ARM_V7`. What do you think?

**Comment by johnplatts** [comment]
> Given the HW is not standards-compliant (in its defence, IEEE-754 changed between 2008 and 2019), I'd be fine to skip such tests for Armv7. highway_test also contains logic like `HWY_TARGET <= HWY_NEON_WITHOUT_AES && HWY_ARCH_ARM_V7`. What do you think?

I have already made a change to HypotTestCases to ignore the Inf/NaN test cases on Armv7 NEON.

**Review by jan-wassenberg — APPROVED** [review]
👍

**Pull request merged**
