### PR TITLE
Refactor thread pool

### PR DESCRIPTION
**Pull request by clin99**

### CODE REVIEW

**Comment by jan-wassenberg** [comment]
Thanks @clin99 for the pull request :) Are you able to sign the [CLA](https://cla.developers.google.com/)?

**Comment by clin99** [comment]
@jan-wassenberg Yes, I will read and sign the CLA by tomorrow (Oct 3), thanks very much for reviewing the code!

**Comment by clin99** [comment]
@jan-wassenberg   It has come to my attention that an approval from my employer is required to sign the CLA. I am currently waiting for their approval which might span a few days to a maximum of three weeks (hopefully not that long). I apologize for any inconvenience this may cause and appreciate your patience.

**Comment by jan-wassenberg** [comment]
I understand, thanks for the heads-up 👍

**Comment by clin99** [comment]
@jan-wassenberg I have signed the CLA. Thank you again for your patience!

**Review by jan-wassenberg — APPROVED** [review]
Thank you for arranging the CLA and following up :)

**Pull request merged**
