### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by GoodDaisy**

### CODE REVIEW

**Comment by jan-wassenberg** [comment]
Hi @GoodDaisy , are you able to sign the [CLA](https://cla.developers.google.com/)?

**Comment by GoodDaisy** [comment]
I should have signed the CLA, I don't know why it always shows failing.

**Comment by jan-wassenberg** [comment]
:) Is it possible that the CLA has been signed by a different email address than the one used in this PR (r***z​@consenlabs.com)?

**Comment by GoodDaisy** [comment]
@jan-wassenberg yeah... I am lost in CLA. I commited PR with github email, but signed in google with another one. How to resolve it?

**Comment by jan-wassenberg** [comment]
Hi @GoodDaisy, sorry to reply late. Is it possible to re-push or recreate the pull request using the other email address that already has the CLA?
Alternatively, are you able to sign the CLA again just using this other email address?

**Comment by jan-wassenberg** [comment]
It is fixed, thanks :)

**Pull request closed without merging**
